defaults:
  - hpo: optuna

mlflow:
  tracking_uri: "http://127.0.0.1:5000"
  experiment_name: "HPO_Optuna_Experiment_LAB_3"
  log_model: true
  register_model: true
  best_model_name: "best_model_optuna_random_forest"
  stage: "Staging"

data:
  processed_path: "data/prepared/train.csv"
  target_column: "Churn"
  test_size: 0.2
  random_state: 42

model:
  type: "RandomForestClassifier"

hpo:
  n_trials: 50
  sampler: "random"
  metric: "f1"
  direction: "maximize"
  use_cv: False
  cv_folds: 5

  random_forest:
    n_estimators:
      distribution: "int"
      low: 50
      high: 200
    max_depth:
      distribution: "int"
      low: 5
      high: 20
    min_samples_split:
      distribution: "int"
      low: 2
      high: 10
    min_samples_leaf:
      distribution: "int"
      low: 1
      high: 4

hydra:
  run:
    dir: .
  output_subdir: null